import { Path } from "react-hook-form";

import type { PromotionFormData, RewardFormData } from "@/types/hooks";

import type { PromotionRewardPath } from "./qualifyCondition.paths";
import type { TimeframePaths } from "./TimeframeForm";
import type { UsageConditionsFormPaths } from "./UsageConditionsForm";

type PromotionRewardUsageBasePath = `${PromotionRewardPath}.usageConditions`;

export const buildPromotionRewardUsagePaths = (
  fieldPath: PromotionRewardPath,
  p: (value: Path<PromotionFormData>) => Path<PromotionFormData>
): UsageConditionsFormPaths<PromotionFormData> => {
  const usageBase: PromotionRewardUsageBasePath = `${fieldPath}.usageConditions`;
  const usageTimeframeBase = `${usageBase}.timeframe` as const;
  const usageTimeframePaths = {
    mode: p(`${usageTimeframeBase}.mode`),
    start: p(`${usageTimeframeBase}.start`),
    end: p(`${usageTimeframeBase}.end`),
    anchorEntityType: p(`${usageTimeframeBase}.anchor.entityType`),
    anchorEntityRefType: p(`${usageTimeframeBase}.anchor.entityRefType`),
    anchorEntityRef: p(`${usageTimeframeBase}.anchor.entityRef`),
    anchorEvent: p(`${usageTimeframeBase}.anchor.event`),
    offsetDays: p(`${usageTimeframeBase}.offsetDays`),
  } satisfies TimeframePaths<PromotionFormData>;

  return {
    type: p(`${usageBase}.type`),
    freebet: {
      timeframe: usageTimeframePaths,
      mustUseComplete: p(`${usageBase}.mustUseComplete`),
      lockWinningsUntilFullyUsed: p(`${usageBase}.lockWinningsUntilFullyUsed`),
      voidConsumesBalance: p(`${usageBase}.voidConsumesBalance`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
    },
    rollover: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      multiplier: p(`${usageBase}.multiplier`),
      maxConversionMultiplier: p(`${usageBase}.maxConversionMultiplier`),
      expectedLossPercentage: p(`${usageBase}.expectedLossPercentage`),
      minBetsRequired: p(`${usageBase}.minBetsRequired`),
      bonusCanBeUsedForBetting: p(`${usageBase}.bonusCanBeUsedForBetting`),
      rolloverContributionWallet: p(`${usageBase}.rolloverContributionWallet`),
      realMoneyUsageRatio: p(`${usageBase}.realMoneyUsageRatio`),
      noWithdrawalsAllowedDuringRollover: p(`${usageBase}.noWithdrawalsAllowedDuringRollover`),
      bonusCancelledOnWithdrawal: p(`${usageBase}.bonusCancelledOnWithdrawal`),
      allowDepositsAfterActivation: p(`${usageBase}.allowDepositsAfterActivation`),
      returnedBetsCountForRollover: p(`${usageBase}.returnedBetsCountForRollover`),
      cashoutBetsCountForRollover: p(`${usageBase}.cashoutBetsCountForRollover`),
      requireResolvedWithinTimeframe: p(`${usageBase}.requireResolvedWithinTimeframe`),
      countOnlySettledBets: p(`${usageBase}.countOnlySettledBets`),
      maxConvertibleAmount: p(`${usageBase}.maxConvertibleAmount`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      requiredBetOutcome: p(`${usageBase}.requiredBetOutcome`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    cashback: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      requiredBetOutcome: p(`${usageBase}.requiredBetOutcome`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    bonusNoRollover: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      maxConversionMultiplier: p(`${usageBase}.maxConversionMultiplier`),
      maxConvertibleAmount: p(`${usageBase}.maxConvertibleAmount`),
      returnedBetsCountForUsage: p(`${usageBase}.returnedBetsCountForUsage`),
      cashoutBetsCountForUsage: p(`${usageBase}.cashoutBetsCountForUsage`),
      requireResolvedWithinTimeframe: p(`${usageBase}.requireResolvedWithinTimeframe`),
      countOnlySettledBets: p(`${usageBase}.countOnlySettledBets`),
      onlyFirstBetCounts: p(`${usageBase}.onlyFirstBetCounts`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      requiredBetOutcome: p(`${usageBase}.requiredBetOutcome`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    enhancedOdds: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      normalOdds: p(`${usageBase}.normalOdds`),
      enhancedOdds: p(`${usageBase}.enhancedOdds`),
      enhancedOddsMode: p(`${usageBase}.enhancedOddsMode`),
      enhancementPercentage: p(`${usageBase}.enhancementPercentage`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    casinoSpins: {
      timeframe: usageTimeframePaths,
      spinsCount: p(`${usageBase}.spinsCount`),
      gameTitle: p(`${usageBase}.gameTitle`),
    },
  };
};

export const buildRewardStandaloneUsagePaths = (
  p: (value: Path<RewardFormData>) => Path<RewardFormData>
): UsageConditionsFormPaths<RewardFormData> => {
  const usageBase = "usageConditions" as const;
  const usageTimeframeBase = `${usageBase}.timeframe` as const;
  const usageTimeframePaths = {
    mode: p(`${usageTimeframeBase}.mode`),
    start: p(`${usageTimeframeBase}.start`),
    end: p(`${usageTimeframeBase}.end`),
    anchorEntityType: p(`${usageTimeframeBase}.anchor.entityType`),
    anchorEntityRefType: p(`${usageTimeframeBase}.anchor.entityRefType`),
    anchorEntityRef: p(`${usageTimeframeBase}.anchor.entityRef`),
    anchorEvent: p(`${usageTimeframeBase}.anchor.event`),
    offsetDays: p(`${usageTimeframeBase}.offsetDays`),
  } satisfies TimeframePaths<RewardFormData>;

  return {
    type: p(`${usageBase}.type`),
    freebet: {
      timeframe: usageTimeframePaths,
      mustUseComplete: p(`${usageBase}.mustUseComplete`),
      lockWinningsUntilFullyUsed: p(`${usageBase}.lockWinningsUntilFullyUsed`),
      voidConsumesBalance: p(`${usageBase}.voidConsumesBalance`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
    },
    rollover: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      multiplier: p(`${usageBase}.multiplier`),
      maxConversionMultiplier: p(`${usageBase}.maxConversionMultiplier`),
      expectedLossPercentage: p(`${usageBase}.expectedLossPercentage`),
      minBetsRequired: p(`${usageBase}.minBetsRequired`),
      bonusCanBeUsedForBetting: p(`${usageBase}.bonusCanBeUsedForBetting`),
      rolloverContributionWallet: p(`${usageBase}.rolloverContributionWallet`),
      realMoneyUsageRatio: p(`${usageBase}.realMoneyUsageRatio`),
      noWithdrawalsAllowedDuringRollover: p(`${usageBase}.noWithdrawalsAllowedDuringRollover`),
      bonusCancelledOnWithdrawal: p(`${usageBase}.bonusCancelledOnWithdrawal`),
      allowDepositsAfterActivation: p(`${usageBase}.allowDepositsAfterActivation`),
      returnedBetsCountForRollover: p(`${usageBase}.returnedBetsCountForRollover`),
      cashoutBetsCountForRollover: p(`${usageBase}.cashoutBetsCountForRollover`),
      requireResolvedWithinTimeframe: p(`${usageBase}.requireResolvedWithinTimeframe`),
      countOnlySettledBets: p(`${usageBase}.countOnlySettledBets`),
      maxConvertibleAmount: p(`${usageBase}.maxConvertibleAmount`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      requiredBetOutcome: p(`${usageBase}.requiredBetOutcome`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    cashback: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      requiredBetOutcome: p(`${usageBase}.requiredBetOutcome`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    bonusNoRollover: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      maxConversionMultiplier: p(`${usageBase}.maxConversionMultiplier`),
      maxConvertibleAmount: p(`${usageBase}.maxConvertibleAmount`),
      returnedBetsCountForUsage: p(`${usageBase}.returnedBetsCountForUsage`),
      cashoutBetsCountForUsage: p(`${usageBase}.cashoutBetsCountForUsage`),
      requireResolvedWithinTimeframe: p(`${usageBase}.requireResolvedWithinTimeframe`),
      countOnlySettledBets: p(`${usageBase}.countOnlySettledBets`),
      onlyFirstBetCounts: p(`${usageBase}.onlyFirstBetCounts`),
      oddsMin: p(`${usageBase}.oddsRestriction.minOdds`),
      oddsMax: p(`${usageBase}.oddsRestriction.maxOdds`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      requiredBetOutcome: p(`${usageBase}.requiredBetOutcome`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    enhancedOdds: {
      timeframe: usageTimeframePaths,
      allowMultipleBets: p(`${usageBase}.allowMultipleBets`),
      normalOdds: p(`${usageBase}.normalOdds`),
      enhancedOdds: p(`${usageBase}.enhancedOdds`),
      enhancedOddsMode: p(`${usageBase}.enhancedOddsMode`),
      enhancementPercentage: p(`${usageBase}.enhancementPercentage`),
      stakeMin: p(`${usageBase}.stakeRestriction.minStake`),
      stakeMax: p(`${usageBase}.stakeRestriction.maxStake`),
      multipleMinSelections: p(`${usageBase}.multipleBetCondition.minSelections`),
      multipleMaxSelections: p(`${usageBase}.multipleBetCondition.maxSelections`),
      multipleMinOddsPerSelection: p(`${usageBase}.multipleBetCondition.minOddsPerSelection`),
      multipleMaxOddsPerSelection: p(`${usageBase}.multipleBetCondition.maxOddsPerSelection`),
      allowLiveOddsChanges: p(`${usageBase}.allowLiveOddsChanges`),
      betTypeRestrictions: p(`${usageBase}.betTypeRestrictions`),
      selectionRestrictions: p(`${usageBase}.selectionRestrictions`),
      otherRestrictions: p(`${usageBase}.otherRestrictions`),
    },
    casinoSpins: {
      timeframe: usageTimeframePaths,
      spinsCount: p(`${usageBase}.spinsCount`),
      gameTitle: p(`${usageBase}.gameTitle`),
    },
  };
};
